require_relative 'lib/string.rb'
require_relative 'lib/syllable_dictionary.rb'
require_relative 'lib/web_scraper.rb'
require_relative 'lib/haiku_builder.rb'
require 'twitter'
require 'nokogiri'
require 'open-uri'