<<<<<<< HEAD
require_relative '../lib/string.rb'
require_relative '../lib/syllable_dictionary.rb'
=======
require_relative '../Haiku.rb'
require 'webmock/rspec'
require 'nokogiri'
require 'twitter'
require 'vcr'
>>>>>>> 62e586deac507490dfd8bd098e90dfa5c2809cf2


# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.include WebMock::API
  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end



VCR.configure do |c|
	c.cassette_library_dir = 'spec/cassettes'
	c.hook_into :webmock
	c.configure_rspec_metadata!
end
